on: [push]

jobs:
  govulncheck_job:
    runs-on: ubuntu-latest
    name: Run govulncheck
    strategy:
      matrix:
        go-version: [1.19.x, 1.20.x]
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
           go-version-input: ${{ matrix.go-version }}
           go-package: ./...
