name: Nix formatter checks

on:
  pull_request:
  push:
    branches:
      - master
jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Install Nix
        uses: cachix/install-nix-action@v26

      - name: Run nix formatter tool
        run: nix fmt . -- --fail-on-change

